/* Private dashboard client: financial API calls always require a Shopify ID token. */
const $=s=>document.querySelector(s), config=window.PROFIT_CONFIG;
let report=null,currentTab='overview',loading=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=v=>v==null?'—':new Intl.NumberFormat('sv-SE',{maximumFractionDigits:0}).format(v/100)+' kr';
const inputMoney=v=>v==null?'':(v/100).toFixed(2);
const num=v=>String(v).trim()===''?null:Number(v);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,5000);}
async function api(path,method='GET',body){
 let token=config.preview?new URLSearchParams(location.hash.slice(1)).get('key'):await window.shopify?.idToken();
 if(!token)throw Error('Open Profit from your Shopify admin to sign in.');
 const r=await fetch('/profit/api/'+path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
 const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;
}
function dates(){const d=new Date(today()+'T12:00:00Z'),p=$('#preset').value;let from=new Date(d),to=new Date(d);
 if(p==='month')from.setUTCDate(1);else if(p==='lastmonth'){from.setUTCDate(1);from.setUTCMonth(from.getUTCMonth()-1);to.setUTCDate(0);}else if(p==='7'||p==='30')from.setUTCDate(from.getUTCDate()-Number(p)+1);
 if(p!=='custom'){$('#from').value=from.toISOString().slice(0,10);$('#to').value=to.toISOString().slice(0,10);}}
async function load(){if(loading)return;loading=true;try{report=await api('report?'+new URLSearchParams({from:$('#from').value,to:$('#to').value}));$('#fatal').hidden=true;$('#content').hidden=false;render();}catch(e){$('#fatal').hidden=false;$('#fatal').textContent=e.message;}finally{loading=false;}}
function table(headers,rows){return rows.length?'<div class="tablewrap"><table class="table"><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>':'<div class="empty">Nothing to show for this selection.</div>';}
function orderRows(orders){return orders.map(o=>'<tr><td><button class="button small" data-order="'+esc(o.id)+'">'+esc(o.name)+'</button><small>'+o.day+'</small></td><td class="title">'+esc(o.lines.map(l=>l.title).join(', '))+'</td><td>'+cash(o.netSales)+'</td><td>'+cash(o.cogs)+(o.missingCost?' <span class="badge warn">Missing</span>':'')+'</td><td>'+cash(o.fees)+(o.missingFees?' <span class="badge warn">Review</span>':'')+'</td><td>'+cash(o.tax)+'</td><td class="'+(o.profitBeforeVat<0?'negative':'positive')+'">'+cash(o.profitBeforeVat)+'</td><td class="'+(o.profit<0?'negative':'positive')+'">'+cash(o.profit)+'</td><td><span class="badge '+(!o.eligible?'red':o.complete?'':'warn')+'">'+(!o.eligible?'Excluded':o.complete?'Complete':'Estimate / review')+'</span></td></tr>');}
function render(){
 const t=report.totals,missing=report.missingCosts,unknown=t.missingCost||t.missingFees;
 const excluded=report.excludedOrders||[];
 $('#costBadge').textContent=missing.length;
 const sync=report.sync;$('#syncStatus').textContent=sync.status==='ready'?'Updated '+new Date(sync.completed).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):sync.status==='syncing'?'Syncing…':sync.status==='error'?'Sync needs attention':'First sync pending';
 let notice=[];if(excluded.length)notice.push(excluded.length+' non-SEK order(s) excluded from these totals; review Orders');if(sync.historyFrom&&report.from<sync.historyFrom.slice(0,10))notice.push('Selected dates extend beyond imported order history');if(t.missingCost)notice.push(t.missingCost+' sold item'+(t.missingCost===1?'':'s')+' missing purchase costs');if(t.missingFees)notice.push(t.missingFees+' orders with unconfirmed fees');if(t.missingShipping||t.missingPackaging)notice.push('Shipping / packaging expenses are incomplete');if(t.incomplete&&!unknown)notice.push('Some costs are estimated or need confirmation');if(report.settings.taxBasis!=='shopify')notice.push('VAT basis needs confirmation');if(sync.status==='error')notice.push('Latest sync failed; figures may be incomplete');
 $('#notice').hidden=!notice.length;$('#notice').innerHTML='<div><strong>'+esc(notice.join(' · '))+'</strong><div class="mini">Missing amounts are not confirmed zero. Review the order details before relying on the result.</div></div><button class="button small" data-tab="costs">Review costs</button>';
 const kpis=[['Sales including VAT',cash(t.revenue),t.orders+' paid / refunded orders; refunds deducted'],['Item purchase costs',cash(t.cogs),t.missingCost?t.missingCost+' costs still missing':'Costs saved per order'],['Payment fees',cash(t.fees),t.missingFees?t.missingFees+' orders need fee confirmation':'Reported transaction fees'],['Profit before VAT',unknown?'—':cash(t.beforeVat),(unknown?'Pending · ':'Estimated · ')+cash(t.beforeVat)+' after recorded costs'],['Recorded VAT',cash(t.tax),'Shopify VAT or your order adjustments'],['Profit after VAT',unknown?'—':cash(t.result),(unknown?'Pending · ':'Estimated · ')+cash(t.result)+' after recorded costs; before income tax']];
 if(excluded.length){kpis[3][2]='Partial report · excludes '+excluded.length+' non-SEK order(s)';kpis[5][2]='Partial report · excludes '+excluded.length+' non-SEK order(s)';}
 $('#kpis').innerHTML=kpis.map((k,i)=>'<div class="card '+(i===3||i===5?'kpi-green':'')+'"><div class="kpi-label">'+k[0]+'</div><div class="kpi-value">'+k[1]+'</div><div class="kpi-foot">'+k[2]+'</div></div>').join('');
 $('#breakdown').innerHTML=[['Sales including VAT (after refunds)',t.revenue],['Item costs',-t.cogs],['Payment fees',-t.fees],['Shipping & packaging',-t.shipping-t.packaging],['Business expenses',-t.expenses],['Before VAT · recorded costs only',t.beforeVat],['Recorded VAT',-t.tax],['After VAT · recorded costs only',t.result]].map((r,i)=>'<div class="breakdown '+(i===5||i===7?'total':'')+'"><span>'+r[0]+'</span><span>'+((i===3&&(t.missingShipping||t.missingPackaging))?cash(r[1])+' recorded':cash(r[1]))+'</span></div>').join('');
 $('#recent').innerHTML=table(['Order','Item','Net sales','Cost','Fees','VAT','Before VAT','After VAT','Status'],orderRows(report.orders.filter(o=>o.eligible).slice(0,5)));
 $('#methods').innerHTML=report.methods.map(m=>'<div class="breakdown"><div>'+esc(m.method.replaceAll('_',' '))+'<div class="muted mini">'+m.orders+' orders</div></div><strong>'+cash(m.fees)+(m.missing?'<small class="muted mini" style="display:block">'+m.missing+' unconfirmed</small>':'')+'</strong></div>').join('')||'<p class="muted">No payments in this period.</p>';
 renderOrders();renderCosts();renderExpenses();chart();
 const s=report.settings;for(const k of ['shippingDefault','packagingDefault'])$('#settingsForm').elements[k].value=inputMoney(s[k]);$('#settingsForm').elements.taxBasis.value=s.taxBasis||'unconfirmed';
 $('#coverage').textContent='SEK · Europe/Stockholm · Order-date basis: refunds update the original order period. '+(sync.historyFrom?'Imported order history starts '+sync.historyFrom.slice(0,10)+'. Older periods may be incomplete. ':'Initial sync has not completed. ')+(sync.message?'Sync: '+sync.message:'');
}
function renderOrders(){$('#excludedOrders').innerHTML=(report.excludedOrders||[]).map(o=>'<p class="notice"><strong>'+esc(o.name)+' · '+esc(o.currency)+'</strong> '+esc(o.reason)+'</p>').join('');const q=$('#orderSearch').value.toLowerCase();$('#orderTable').innerHTML=table(['Order','Item','Net sales','Item cost','Fees','VAT','Before VAT','After VAT','Status'],orderRows(report.orders.filter(o=>(o.name+' '+o.lines.map(l=>l.title).join(' ')).toLowerCase().includes(q))));}
function renderCosts(){const q=$('#costSearch').value.toLowerCase();$('#costTable').innerHTML=table(['Product','SKU','In stock','Action'],report.missingCosts.filter(v=>(v.title+' '+(v.sku||'')).toLowerCase().includes(q)).map(v=>'<tr><td class="title"><a target="_blank" rel="noopener" href="https://admin.shopify.com/store/'+config.store.split('.')[0]+'/products/'+v.product_id.split('/').pop()+'">'+esc(v.title)+'</a></td><td>'+esc(v.sku||'—')+'</td><td>'+v.quantity+'</td><td><button class="button small" data-variant="'+esc(v.id)+'">Add cost</button></td></tr>'));
 $('#soldMissing').innerHTML=table(['Order','Item','Net sales','Cost','Fees','VAT','Before VAT','After VAT','Status'],orderRows(report.orders.filter(o=>o.eligible&&o.missingCost)));}
function renderExpenses(){$('#expenseTable').innerHTML=table(['Date','Category','Description','Amount',''],report.expenses.map(e=>'<tr><td>'+e.day+'</td><td>'+esc(e.category)+'</td><td class="title">'+esc(e.description)+'</td><td>'+cash(e.amount)+'</td><td><button class="button small danger" data-delete="'+e.id+'">Remove</button></td></tr>'));}
function chart(){const before=$('#chartVat').value==='before';$('#salesLegend').textContent=before?'Sales including VAT':'Sales excluding VAT';$('#profitLegend').textContent=before?'Before VAT · recorded costs':'After VAT · recorded costs';let groups=report.days.map(d=>({...d,netSales:before?d.revenue:d.netSales,result:before?d.beforeVat:d.result}));if($('#groupBy').value==='month'){const m=new Map();for(const d of groups){const key=d.day.slice(0,7),v=m.get(key)||{day:key,netSales:0,result:0,missing:0};v.netSales+=d.netSales;v.result+=d.result;v.missing+=d.missing;m.set(key,v);}groups=[...m.values()];}
 if(!groups.length){$('#chart').innerHTML='<div class="empty">No sales yet in this period.</div>';return;}
 const width=650,height=210,top=14,bottom=180,values=groups.flatMap(d=>[d.netSales,d.result]),high=Math.max(1,...values),low=Math.min(0,...values),scale=(bottom-top)/(high-low),base=top+high*scale,step=width/groups.length,bw=Math.max(2,Math.min(22,step*.3));
 let svg='<svg viewBox="0 0 '+width+' '+height+'" width="100%" height="100%" role="img" aria-label="Sales and result after recorded costs">';
 for(let i=0;i<4;i++){const y=top+(base-top)*i/3;svg+='<line x1="0" x2="650" y1="'+y+'" y2="'+y+'" stroke="#edf1eb"/>';}
 groups.forEach((d,i)=>{const x=step*i+step/2;[d.netSales,d.result].forEach((value,j)=>{const h=Math.abs(value)*scale;svg+='<rect x="'+(x+(j?1:-bw-1))+'" y="'+(value>=0?base-h:base)+'" width="'+bw+'" height="'+h+'" rx="2" fill="'+(j?'#c4d7c9':'#377e63')+'"><title>'+esc(d.day+': '+(j?(before?'Before VAT ':'After VAT '):(before?'Sales including VAT ':'Sales excluding VAT '))+cash(value)+(d.missing?' (incomplete / estimated)':''))+'</title></rect>';});if(groups.length<12||i%Math.ceil(groups.length/8)===0)svg+='<text x="'+x+'" y="204" text-anchor="middle" font-size="10" fill="#687775">'+d.day.slice(5)+'</text>';});$('#chart').innerHTML=svg+'</svg>';}
function tab(name){currentTab=name;for(const e of document.querySelectorAll('section.section'))e.hidden=e.id!==name;for(const b of document.querySelectorAll('.nav button'))b.classList.toggle('active',b.dataset.tab===name);$('#heading').textContent={overview:'Profit overview',orders:'Order profitability',costs:'Missing purchase costs',expenses:'Business expenses',settings:'Calculation settings'}[name];}
function dialog(title,html){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;$('#dialog').showModal();}
function orderDialog(id){const o=report.orders.find(o=>o.id===id),a=o.adjustments||{};
 dialog(o.name+' · '+cash(o.netSales)+' net sales','<div class="breakdown"><span>Profit before VAT</span><strong>'+cash(o.profitBeforeVat)+'</strong></div><div class="breakdown"><span>Recorded VAT</span><strong>'+cash(o.tax)+'</strong></div><div class="breakdown total"><span>Profit after VAT</span><strong>'+cash(o.profit)+'</strong></div><p class="muted mini">'+esc([...o.issues,...o.notes].join(' · ')||'All recorded inputs are complete.')+'</p>'+o.lines.map(l=>'<form class="line-cost forms" data-order="'+esc(o.id)+'" data-line="'+esc(l.id)+'"><label>'+esc(l.title)+' · '+l.units+' unit(s)<input name="cost" type="number" min="0" step="0.01" required value="'+inputMoney(l.unitCost)+'" placeholder="Purchase cost per unit"></label><button class="button small" type="submit">Save / confirm this order’s cost</button><small class="muted">'+esc(l.source.replaceAll('_',' '))+'</small></form>').join('<hr style="border:0;border-top:1px solid #dce4df;margin:18px 0">')+'<hr style="border:0;border-top:1px solid #dce4df;margin:22px 0"><form id="orderExpenses" class="forms" data-order="'+esc(o.id)+'"><h2>Order expenses and adjustments</h2><p class="muted mini">Leave a fee or tax override blank to use Shopify’s data. Enter 0 only if confirmed. Actual reported fees: '+cash(o.fees)+'.</p>'+[['shipping','Shipping expense',a.shipping_cost],['packaging','Packaging expense',a.packaging_cost],['fees','Total payment fees override',a.fee_override],['tax','VAT amount override',a.tax_override]].map(([key,label,val])=>'<label>'+label+'<input name="'+key+'" type="number" step="0.01" min="0" value="'+inputMoney(val)+'" placeholder="'+(key==='fees'||key==='tax'?'Use Shopify data':'Unknown / use default')+'"></label>').join('')+'<label>Note<input name="note" maxlength="1000" value="'+esc(a.note||'')+'"></label><button class="button primary" type="submit">Save order expenses</button></form>');}
function variantDialog(id){const v=report.missingCosts.find(v=>v.id===id);dialog('Add purchase cost','<p>'+esc(v.title)+'</p><form id="variantCost" class="forms" data-variant="'+esc(id)+'"><label>Purchase cost per item (SEK)<input name="cost" type="number" min="0" step="0.01" required></label><label class="inline"><input type="checkbox" name="applyMissing">Also apply to past orders missing a cost for this variant</label><p class="muted mini">This saves Shopify’s cost per item. Existing saved order costs are preserved.</p><button class="button primary" type="submit">Save Shopify cost</button></form>');}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab)tab(b.dataset.tab);if(b.dataset.order)orderDialog(b.dataset.order);if(b.dataset.variant)variantDialog(b.dataset.variant);if(b.dataset.delete){if(!confirm('Remove this recorded expense?'))return;b.disabled=true;try{await api('expenses/'+b.dataset.delete,'DELETE');await load();}catch(err){toast(err.message);}finally{b.disabled=false;}}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['settingsForm','orderExpenses','variantCost','expenseForm'].includes(f.id)&&!f.classList.contains('line-cost'))return;e.preventDefault();const b=f.querySelector('button[type=submit]');b.disabled=true;try{const data=Object.fromEntries(new FormData(f));
 if(f.id==='settingsForm')await api('settings','PUT',{shippingDefault:num(data.shippingDefault),packagingDefault:num(data.packagingDefault),taxBasis:data.taxBasis});
 else if(f.id==='orderExpenses')await api('order-expenses','PUT',{orderId:f.dataset.order,shipping:num(data.shipping),packaging:num(data.packaging),fees:num(data.fees),tax:num(data.tax),note:data.note});
 else if(f.id==='variantCost')await api('variant-cost','PUT',{variantId:f.dataset.variant,cost:num(data.cost),applyMissing:!!data.applyMissing});
 else if(f.id==='expenseForm')await api('expenses','POST',{...data,amount:num(data.amount)});
 else await api('order-cost','PUT',{orderId:f.dataset.order,lineId:f.dataset.line,cost:num(data.cost)});
 toast('Saved');if($('#dialog').open)$('#dialog').close();await load();
 }catch(err){toast(err.message);}finally{b.disabled=false;}});
$('#addExpense').onclick=()=>dialog('Add business expense','<form id="expenseForm" class="forms"><label>Date<input name="day" type="date" required value="'+today()+'"></label><label>Category<select name="category">'+['Advertising','Shopify & apps','Rent','Payroll','Other'].map(c=>'<option>'+c+'</option>').join('')+'</select></label><label>Description<input name="description" required maxlength="200"></label><label>Amount in SEK (excluding recoverable VAT)<input name="amount" type="number" min="0.01" step="0.01" required></label><button class="button primary" type="submit">Add expense</button></form>');
$('#closeDialog').onclick=()=>$('#dialog').close();$('#preset').onchange=()=>{dates();load();};$('#apply').onclick=()=>{$('#preset').value='custom';load();};$('#orderSearch').oninput=renderOrders;$('#costSearch').oninput=renderCosts;$('#groupBy').onchange=chart;$('#chartVat').onchange=chart;
$('#syncButton').onclick=async()=>{const b=$('#syncButton');b.disabled=true;try{await api('sync','POST');toast('Sync started');for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,3000));await load();if(report?.sync.status==='ready'||report?.sync.status==='error')break;}}catch(e){toast(e.message);}finally{b.disabled=false;}};
$('#export').onclick=()=>{if(!report)return;const rows=[['Order','Date','Sales including VAT SEK','VAT SEK','Net sales SEK','Item cost SEK','Fees SEK','Shipping SEK','Packaging SEK','Profit before VAT SEK','Profit after VAT SEK','Status','Missing inputs'],...report.orders.map(o=>[o.name,o.day,o.revenue/100,o.tax/100,o.netSales/100,o.cogs/100,o.fees/100,o.shipping==null?'':o.shipping/100,o.packaging==null?'':o.packaging/100,o.profitBeforeVat==null?'':o.profitBeforeVat/100,o.profit==null?'':o.profit/100,o.eligible?'Included':'Excluded',o.issues.join('; ')]),...(report.excludedOrders||[]).map(o=>[o.name,'','','','','','','','','','','Excluded',o.reason+' Currency: '+o.currency])];const quote=v=>'"'+(typeof v==='string'&&/^[=+@-]/.test(v)?"'":'')+String(v).replaceAll('"','""')+'"';const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='circular-fash-profit-'+report.from+'-'+report.to+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
dates();load();
