export const requestCertificatePage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Request your certificate | Circular Fash</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f7f7f4;color:#10141f;font:16px/1.6 Arial,sans-serif}main{max-width:620px;margin:48px auto;padding:40px;background:white;border:1px solid #d9dce5}.brand{font-weight:800;letter-spacing:.12em;color:#0e1b4d;text-decoration:none;font-size:14px}h1{font-size:32px;line-height:1.2;margin:30px 0 16px}p{color:#525866}label{display:block;font-weight:700;margin:22px 0 7px}input{width:100%;padding:14px;border:1px solid #939aa8;border-radius:3px;font:inherit}input:focus,button:focus,a:focus{outline:3px solid #4770db;outline-offset:3px}button{width:100%;margin-top:26px;padding:16px;border:0;background:#0e1b4d;color:white;font:700 15px Arial;cursor:pointer}button:disabled{opacity:.6;cursor:wait}.help{font-size:14px}.trap{position:absolute;left:-9999px}#message{padding:14px;background:#f0f3fa;margin-top:20px}a{color:#0e1b4d}@media(max-width:640px){main{margin:0;padding:28px 22px;border:0;min-height:100vh}}</style></head>
<body><main><a class="brand" href="https://circularfash.com">CIRCULAR FASH</a><h1>Request your authenticity certificate</h1>
<p>Purchased before certificates were introduced? You can request one for your past order here. You can also request another copy of an existing certificate.</p>
<form id="request"><label for="order">Order number</label><input id="order" name="orderNumber" placeholder="#3478" autocomplete="off" required maxlength="20" pattern="#?[0-9]{1,12}">
<label for="email">Email used at checkout</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254">
<div class="trap" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div>
<button type="submit">Request certificate</button><div id="message" role="status" tabindex="-1" hidden></div></form>
<p class="help">We send certificates only to the email on the order. Older purchases may need a manual check. Cancelled or returned items may not be eligible.</p>
<p class="help">Can't access your checkout email? <a href="https://circularfash.com/pages/contact">Contact us</a> for help.</p>
<noscript><p>Please enable JavaScript to use this form, or contact us with your order number.</p></noscript></main>
<script>const form=document.getElementById('request'),message=document.getElementById('message');form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;message.hidden=true;try{const response=await fetch('/certificate-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await response.json();message.textContent=data.message||'Unable to submit. Please try again later.';if(response.ok)form.reset()}catch{message.textContent='Unable to submit. Please check your connection and try again.'}finally{button.disabled=false;message.hidden=false;message.focus()}});</script></body></html>`;
